version: "3"

services:
  mysql:
    container_name: mysql5
    image: mysql:5.5.60
    restart: always
    ports:
      - "${mysql_port}:${mysql_port}"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "adminadmin"
    command: --max_allowed_packet=32505856      
  solo:
    container_name: solo
    image: b3log/solo:latest
    restart: always
    ports:
      - "${solo_port}:${solo_port}"
#./solo/skins/  必须有皮肤
#    volumes:
#      - ./solo/skins/:/opt/solo/skins/   
    environment:
      RUNTIME_DB: "MYSQL"
      JDBC_USERNAME: "root"
      JDBC_PASSWORD: "adminadmin"
      JDBC_DRIVER: "com.mysql.cj.jdbc.Driver"
      JDBC_URL: "jdbc:mysql://${host}:${mysql_port}/solo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC"
    links:
      - "mysql"
    command: --listen_port=${solo_port} --server_scheme=${scheme} --server_port=${solo_port} --server_host=${host}

